language: scala

scala:
  - 2.10.6
  - 2.11.7
  - 2.12.2

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - scripts/travis-publish.sh

env:
  global:
  - secure: jFz1aWhx2zBWz1jNTeqxxfy2+4v25SiJIlO2HGd0Iu3921Rd7lJp+4fnSZlwxcDpIS5/laqu7jAxOR2o2QecBNQBtBMwSFfTFsAnJNHi6c2qB4Ns2HBJrYjoQ/sZFEqoJw62M5/ECU2qK+TzLdDYdULqlF4inlkIrVEj2av7oyw=
  - secure: yK4+dMyjKhoNOvDvUsGR/Q9iYeP4pe6ibKX7o4WkHyTYb9ohS4CrrcpSF2N8eSqAQK7I/CW66tLH01HFPp2vQ4L+zlmJi6bLkxEZCvXXbMBbUMHdaiLvTsvJeu+DlwA1BlGPkAGLrD7SvGK38R7A7NQT3AutEz3V6XUMWWd2CDs=

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acd320c0b11f34dcc2a0
